"""Periodos_unique_constraint

Revision ID: e786cea9d093
Revises: b8b89325e6b1
Create Date: 2026-05-25 23:06:39.338775+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e786cea9d093'
down_revision: Union[str, Sequence[str], None] = 'b8b89325e6b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('UkPeriodosLegislaturaAnioNumeroTipo', 'Periodos', ['LegislaturaId', 'AnioLegislativo', 'Numero', 'Tipo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('UkPeriodosLegislaturaAnioNumeroTipo', 'Periodos', type_='unique')
    # ### end Alembic commands ###
