"""Inicial

Revision ID: 5a91aeffbe1b
Revises: 
Create Date: 2026-05-25 19:10:12.572771+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a91aeffbe1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Estados',
    sa.Column('Id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('Clave', sa.String(length=5), nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('Id', name=op.f('PkEstados')),
    sa.UniqueConstraint('Clave', name=op.f('UkEstadosClave')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('Legisladores',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('NombreCompleto', sa.String(length=300), nullable=False),
    sa.Column('Nombre', sa.String(length=150), nullable=True),
    sa.Column('ApellidoPaterno', sa.String(length=100), nullable=True),
    sa.Column('ApellidoMaterno', sa.String(length=100), nullable=True),
    sa.Column('Genero', sa.Enum('M', 'F', 'X', name='LegisladorGeneroEnum'), nullable=True),
    sa.Column('FechaNacimiento', sa.Date(), nullable=True),
    sa.Column('FotoUrl', sa.String(length=500), nullable=True),
    sa.Column('NombreHash', sa.String(length=64), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('Id', name=op.f('PkLegisladores')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('IdxLegisladoresNombreCompleto', 'Legisladores', ['NombreCompleto'], unique=False)
    op.create_index('IdxLegisladoresNombreHash', 'Legisladores', ['NombreHash'], unique=False)
    op.create_table('Legislaturas',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Numero', sa.String(length=10), nullable=False),
    sa.Column('NumeroArabigo', sa.SmallInteger(), nullable=False),
    sa.Column('FechaInicio', sa.Date(), nullable=False),
    sa.Column('FechaFin', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('Id', name=op.f('PkLegislaturas')),
    sa.UniqueConstraint('Numero', name=op.f('UkLegislaturasNumero')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('Partidos',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Siglas', sa.String(length=20), nullable=False),
    sa.Column('Nombre', sa.String(length=200), nullable=False),
    sa.Column('ColorHex', sa.String(length=7), nullable=True),
    sa.Column('Activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('Id', name=op.f('PkPartidos')),
    sa.UniqueConstraint('Siglas', name=op.f('UkPartidosSiglas')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('ScrapingRuns',
    sa.Column('Id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Fuente', sa.String(length=50), nullable=False),
    sa.Column('Tipo', sa.String(length=50), nullable=False),
    sa.Column('Parametros', sa.JSON(), nullable=True),
    sa.Column('StartedAt', sa.DateTime(), nullable=False),
    sa.Column('FinishedAt', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.Enum('Running', 'Success', 'Partial', 'Failed', name='ScrapingRunStatusEnum'), nullable=False),
    sa.Column('RegistrosNuevos', sa.Integer(), nullable=False),
    sa.Column('RegistrosActualizados', sa.Integer(), nullable=False),
    sa.Column('Errores', sa.Integer(), nullable=False),
    sa.Column('ErrorDetalle', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('Id', name=op.f('PkScrapingRuns')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('IdxScrapingRunsFuenteTipo', 'ScrapingRuns', ['Fuente', 'Tipo'], unique=False)
    op.create_index('IdxScrapingRunsStatusStarted', 'ScrapingRuns', ['Status', 'StartedAt'], unique=False)
    op.create_table('LegisladorPeriodo',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LegisladorId', sa.Integer(), nullable=False),
    sa.Column('LegislaturaId', sa.Integer(), nullable=False),
    sa.Column('Camara', sa.Enum('Diputados', 'Senado', name='LegisladorPeriodoCamaraEnum'), nullable=False),
    sa.Column('PartidoId', sa.Integer(), nullable=True),
    sa.Column('EstadoId', sa.SmallInteger(), nullable=True),
    sa.Column('Distrito', sa.SmallInteger(), nullable=True),
    sa.Column('TipoEleccion', sa.Enum('MayoriaRelativa', 'RepresentacionProporcional', 'PrimeraMinoria', name='LegisladorPeriodoTipoEleccionEnum'), nullable=False),
    sa.Column('Curul', sa.String(length=20), nullable=True),
    sa.Column('EsSuplente', sa.Boolean(), nullable=False),
    sa.Column('SuplenteDeId', sa.Integer(), nullable=True),
    sa.Column('FechaAlta', sa.Date(), nullable=True),
    sa.Column('FechaBaja', sa.Date(), nullable=True),
    sa.Column('MotivoBaja', sa.String(length=200), nullable=True),
    sa.Column('IdExterno', sa.String(length=50), nullable=True),
    sa.Column('Fuente', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['EstadoId'], ['Estados.Id'], name=op.f('FkLegisladorPeriodoEstadoId')),
    sa.ForeignKeyConstraint(['LegisladorId'], ['Legisladores.Id'], name=op.f('FkLegisladorPeriodoLegisladorId')),
    sa.ForeignKeyConstraint(['LegislaturaId'], ['Legislaturas.Id'], name=op.f('FkLegisladorPeriodoLegislaturaId')),
    sa.ForeignKeyConstraint(['PartidoId'], ['Partidos.Id'], name=op.f('FkLegisladorPeriodoPartidoId')),
    sa.ForeignKeyConstraint(['SuplenteDeId'], ['LegisladorPeriodo.Id'], name=op.f('FkLegisladorPeriodoSuplenteDeId')),
    sa.PrimaryKeyConstraint('Id', name=op.f('PkLegisladorPeriodo')),
    sa.UniqueConstraint('LegisladorId', 'LegislaturaId', 'Camara', 'FechaAlta', name='UkLegisladorPeriodoLegisladorLegislatura'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('IdxLegisladorPeriodoIdExterno', 'LegisladorPeriodo', ['IdExterno', 'Fuente'], unique=False)
    op.create_index('IdxLegisladorPeriodoLegislaturaCamara', 'LegisladorPeriodo', ['LegislaturaId', 'Camara'], unique=False)
    op.create_table('Periodos',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LegislaturaId', sa.Integer(), nullable=False),
    sa.Column('AnioLegislativo', sa.SmallInteger(), nullable=False),
    sa.Column('Numero', sa.SmallInteger(), nullable=False),
    sa.Column('Tipo', sa.Enum('Ordinario', 'Extraordinario', name='PeriodoTipoEnum'), nullable=False),
    sa.Column('FechaInicio', sa.Date(), nullable=False),
    sa.Column('FechaFin', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['LegislaturaId'], ['Legislaturas.Id'], name=op.f('FkPeriodosLegislaturaId')),
    sa.PrimaryKeyConstraint('Id', name=op.f('PkPeriodos')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('Sesiones',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LegislaturaId', sa.Integer(), nullable=False),
    sa.Column('PeriodoId', sa.Integer(), nullable=False),
    sa.Column('Camara', sa.Enum('Diputados', 'Senado', name='SesionCamaraEnum'), nullable=False),
    sa.Column('Numero', sa.String(length=20), nullable=True),
    sa.Column('Tipo', sa.Enum('Ordinaria', 'Extraordinaria', 'Solemne', 'Permanente', 'Comision', name='SesionTipoEnum'), nullable=False),
    sa.Column('Fecha', sa.Date(), nullable=False),
    sa.Column('HoraInicio', sa.Time(), nullable=True),
    sa.Column('HoraFin', sa.Time(), nullable=True),
    sa.Column('QuorumInicial', sa.SmallInteger(), nullable=True),
    sa.Column('QuorumFinal', sa.SmallInteger(), nullable=True),
    sa.Column('Estado', sa.Enum('Programada', 'EnCurso', 'Concluida', 'Suspendida', 'Cancelada', name='SesionEstadoEnum'), nullable=False),
    sa.Column('UrlGaceta', sa.String(length=500), nullable=True),
    sa.Column('UrlActa', sa.String(length=500), nullable=True),
    sa.Column('UrlVideo', sa.String(length=500), nullable=True),
    sa.Column('ScrapedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['LegislaturaId'], ['Legislaturas.Id'], name=op.f('FkSesionesLegislaturaId')),
    sa.ForeignKeyConstraint(['PeriodoId'], ['Periodos.Id'], name=op.f('FkSesionesPeriodoId')),
    sa.PrimaryKeyConstraint('Id', name=op.f('PkSesiones')),
    sa.UniqueConstraint('Camara', 'LegislaturaId', 'Fecha', 'Numero', name='UkSesionCamaraLegislaturaFechaNumero'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('IdxSesionEstadoFecha', 'Sesiones', ['Estado', 'Fecha'], unique=False)
    op.create_index('IdxSesionFecha', 'Sesiones', ['Fecha'], unique=False)
    op.create_table('Asistencias',
    sa.Column('Id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('SesionId', sa.Integer(), nullable=False),
    sa.Column('LegisladorPeriodoId', sa.Integer(), nullable=False),
    sa.Column('Estado', sa.Enum('Presente', 'Ausente', 'Justificado', 'ComisionOficial', 'Licencia', 'Desconocido', name='AsistenciaEstadoEnum'), nullable=False),
    sa.Column('HoraRegistro', sa.DateTime(), nullable=True),
    sa.Column('TipoPaseLista', sa.Enum('Inicial', 'Intermedio', 'Final', 'VotacionNominal', name='AsistenciaTipoPaseListaEnum'), nullable=True),
    sa.Column('Fuente', sa.String(length=50), nullable=False),
    sa.Column('ScrapedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['LegisladorPeriodoId'], ['LegisladorPeriodo.Id'], name=op.f('FkAsistenciasLegisladorPeriodoId')),
    sa.ForeignKeyConstraint(['SesionId'], ['Sesiones.Id'], name=op.f('FkAsistenciasSesionId')),
    sa.PrimaryKeyConstraint('Id', name=op.f('PkAsistencias')),
    sa.UniqueConstraint('SesionId', 'LegisladorPeriodoId', 'TipoPaseLista', name='UkAsistenciaSesionLegisladorTipo'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('IdxAsistenciaLegislador', 'Asistencias', ['LegisladorPeriodoId'], unique=False)
    op.create_index('IdxAsistenciaSesion', 'Asistencias', ['SesionId'], unique=False)
    op.create_table('Votaciones',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SesionId', sa.Integer(), nullable=False),
    sa.Column('Numero', sa.SmallInteger(), nullable=False),
    sa.Column('Asunto', sa.Text(), nullable=False),
    sa.Column('Tipo', sa.Enum('Nominal', 'Economica', 'Cedula', name='VotacionTipoEnum'), nullable=False),
    sa.Column('Resultado', sa.Enum('Aprobado', 'Rechazado', 'Empate', 'Retirado', name='VotacionResultadoEnum'), nullable=True),
    sa.Column('TotalFavor', sa.SmallInteger(), nullable=True),
    sa.Column('TotalContra', sa.SmallInteger(), nullable=True),
    sa.Column('TotalAbstencion', sa.SmallInteger(), nullable=True),
    sa.Column('TotalAusente', sa.SmallInteger(), nullable=True),
    sa.Column('Hora', sa.Time(), nullable=True),
    sa.Column('UrlDetalle', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['SesionId'], ['Sesiones.Id'], name=op.f('FkVotacionesSesionId')),
    sa.PrimaryKeyConstraint('Id', name=op.f('PkVotaciones')),
    sa.UniqueConstraint('SesionId', 'Numero', name='UkVotacionSesionNumero'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('Votos',
    sa.Column('Id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('VotacionId', sa.Integer(), nullable=False),
    sa.Column('LegisladorPeriodoId', sa.Integer(), nullable=False),
    sa.Column('Sentido', sa.Enum('Favor', 'Contra', 'Abstencion', 'Ausente', 'Quorum', name='VotoSentidoEnum'), nullable=False),
    sa.ForeignKeyConstraint(['LegisladorPeriodoId'], ['LegisladorPeriodo.Id'], name=op.f('FkVotosLegisladorPeriodoId')),
    sa.ForeignKeyConstraint(['VotacionId'], ['Votaciones.Id'], name=op.f('FkVotosVotacionId')),
    sa.PrimaryKeyConstraint('Id', name=op.f('PkVotos')),
    sa.UniqueConstraint('VotacionId', 'LegisladorPeriodoId', name='UkVotoVotacionLegislador'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Votos')
    op.drop_table('Votaciones')
    op.drop_index('IdxAsistenciaSesion', table_name='Asistencias')
    op.drop_index('IdxAsistenciaLegislador', table_name='Asistencias')
    op.drop_table('Asistencias')
    op.drop_index('IdxSesionFecha', table_name='Sesiones')
    op.drop_index('IdxSesionEstadoFecha', table_name='Sesiones')
    op.drop_table('Sesiones')
    op.drop_table('Periodos')
    op.drop_index('IdxLegisladorPeriodoLegislaturaCamara', table_name='LegisladorPeriodo')
    op.drop_index('IdxLegisladorPeriodoIdExterno', table_name='LegisladorPeriodo')
    op.drop_table('LegisladorPeriodo')
    op.drop_index('IdxScrapingRunsStatusStarted', table_name='ScrapingRuns')
    op.drop_index('IdxScrapingRunsFuenteTipo', table_name='ScrapingRuns')
    op.drop_table('ScrapingRuns')
    op.drop_table('Partidos')
    op.drop_table('Legislaturas')
    op.drop_index('IdxLegisladoresNombreHash', table_name='Legisladores')
    op.drop_index('IdxLegisladoresNombreCompleto', table_name='Legisladores')
    op.drop_table('Legisladores')
    op.drop_table('Estados')
    # ### end Alembic commands ###
