"""ApiKeys_tabla

Revision ID: fb8a1afddda1
Revises: e786cea9d093
Create Date: 2026-05-26 00:21:19.531428+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb8a1afddda1'
down_revision: Union[str, Sequence[str], None] = 'e786cea9d093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ApiKeys',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('KeyHash', sa.String(length=64), nullable=False),
    sa.Column('Nombre', sa.String(length=200), nullable=False),
    sa.Column('Activo', sa.Boolean(), nullable=False),
    sa.Column('RateLimitPerMin', sa.Integer(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('LastUsedAt', sa.DateTime(), nullable=True),
    sa.Column('ExpiresAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id', name=op.f('PkApiKeys')),
    sa.UniqueConstraint('KeyHash', name=op.f('UkApiKeysKeyHash')),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ApiKeys')
    # ### end Alembic commands ###
